//
//  BitcoinHistoryListModels.swift
//  bitcoin-history
//
//  Created by Josep Bordes Jové on 27/11/2019.
//  Copyright (c) 2019 Josep Bordes Jové. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import BHKit

protocol ListResponse {
  var todaySection: BitconHistorySection? { get }
  var historicSection: BitconHistorySection? { get }
  var placeholderSection: BitconHistorySection? { get }
  var error: Error? { get }
}

enum BitcoinHistoryList {
  // MARK: Use cases
  
  enum PrepareView {
    struct Request {
    }
    struct Response: ListResponse {
      var todaySection: BitconHistorySection?
      var historicSection: BitconHistorySection?
      var placeholderSection: BitconHistorySection?
      var error: Error?
    }
    struct ViewModel {
      let title: String
      let result: Result<[BitconHistorySection], Error>
    }
  }
  
  enum ForceUpdateTodaysRate {
    struct Request {
    }
    struct Response: ListResponse {
      var todaySection: BitconHistorySection?
      var historicSection: BitconHistorySection?
      var placeholderSection: BitconHistorySection?
      var error: Error?
    }
    struct ViewModel {
      let result: Result<[BitconHistorySection], Error>
    }
  }
  
  enum StartUpdatingForPrice {
    struct Request {
    }
    struct Response: ListResponse {
      var todaySection: BitconHistorySection?
      var historicSection: BitconHistorySection?
      var placeholderSection: BitconHistorySection?
      var error: Error?
    }
    struct ViewModel {
      let result: Result<[BitconHistorySection], Error>
    }
  }
  
  enum StopUpdatingForPrice {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
}
