//
//  BitcoinPriceDetailRouter.swift
//  bitcoin-history
//
//  Created by Josep Bordes Jové on 27/11/2019.
//  Copyright (c) 2019 Josep Bordes Jové. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BitcoinPriceDetailRoutingLogic {
  func routeToInfoDisclaimer()
}

protocol BitcoinPriceDetailDataPassing {
  var dataStore: BitcoinPriceDetailDataStore? { get }
}

class BitcoinPriceDetailRouter: NSObject, BitcoinPriceDetailRoutingLogic, BitcoinPriceDetailDataPassing {
  weak var viewController: BitcoinPriceDetailViewController?
  var dataStore: BitcoinPriceDetailDataStore?
  
  // MARK: Routing
  
  func routeToInfoDisclaimer() {
    var message = NSLocalizedString("Something basic to inform about the price, disclaiming about the showed info", comment: "")
    
    if let todayDisclaimer = dataStore?.dayRate?.disclaimer {
      message = todayDisclaimer
    }
    
    let alertController = UIAlertController(title: NSLocalizedString("Disclaimer", comment: ""), message: message, preferredStyle: .alert)
    let acceptAction = UIAlertAction(title: NSLocalizedString("Accept", comment: ""), style: .default, handler: nil)
    
    alertController.addAction(acceptAction)
    viewController?.present(alertController, animated: true, completion: nil)
  }

  // MARK: Navigation
  
  //func navigateToSomewhere(source: BitcoinPriceDetailViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: BitcoinPriceDetailDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
