//
//  BitcoinPriceDetailPresenter.swift
//  bitcoin-history
//
//  Created by Josep Bordes Jové on 27/11/2019.
//  Copyright (c) 2019 Josep Bordes Jové. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BitcoinPriceDetailPresentationLogic {
  func presentView(response: BitcoinPriceDetail.PrepareView.Response)
}

class BitcoinPriceDetailPresenter: BitcoinPriceDetailPresentationLogic {
  weak var viewController: BitcoinPriceDetailDisplayLogic?
  
  func presentView(response: BitcoinPriceDetail.PrepareView.Response) {
    switch response.result {
    case .success(let details):
      let sortedDetails = details.sorted { $0.currency.rawValue < $1.currency.rawValue }
      let viewModel = BitcoinPriceDetail.PrepareView.ViewModel(result: .success(sortedDetails))
      viewController?.displayView(viewModel: viewModel)
    case .failure(let error):
      let viewModel = BitcoinPriceDetail.PrepareView.ViewModel(result: .failure(error))
      viewController?.displayView(viewModel: viewModel)
    }
  }
}
