//
//  BitcoinPriceDetailPresenterTests.swift
//  bitcoin-history
//
//  Created by Josep Bordes Jové on 30/11/2019.
//  Copyright (c) 2019 Josep Bordes Jové. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Bitcoin_History
import XCTest
import BHKit

class BitcoinPriceDetailPresenterTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: BitcoinPriceDetailPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupBitcoinPriceDetailPresenter()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupBitcoinPriceDetailPresenter() {
    sut = BitcoinPriceDetailPresenter()
  }
  
  // MARK: Test doubles
  
  class BitcoinPriceDetailDisplayLogicSpy: BitcoinPriceDetailDisplayLogic {
    var displayViewCalled = false

    func displayView(viewModel: BitcoinPriceDetail.PrepareView.ViewModel) {
      displayViewCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentView() {
    // Given
    let spy = BitcoinPriceDetailDisplayLogicSpy()
    sut.viewController = spy
    let response = BitcoinPriceDetail.PrepareView.Response(result: .success([Rate.fake0, Rate.fake1]))
    
    // When
    sut.presentView(response: response)
    
    // Then
    XCTAssertTrue(spy.displayViewCalled, "presentView(response:) should ask the view controller to display the result")
  }
}
